---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb-php
    version: php
  name: myweb-php
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb-php
      version: azure
  template:
    metadata:
      labels:
        app: myweb-php
        version: azure
    spec:
      containers:
      - image: vladreamer/azyre-myweb:55
        imagePullPolicy: IfNotPresent
        name: myweb-php
        resources:
         limits:
           memory: 120Mi
           cpu: "1"
         requests:
           memory: 100Mi
           cpu: "0.2"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb-php
  name: myweb-php-svc
  namespace: default
spec:
  ports:
  - nodePort: 32225
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myweb-php
  #type: LoadBalancer
  type: NodePort
