# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstBuildJob
    steps:
    - bash: echo Buld FirstJob
  - job: SecondBuildJob
    steps:
    - bash: echo Buld SecondJob

- stage: DevDeploy
  dependsOn: Build 
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo Job DevDeploy

- stage: QaDeploy
  dependsOn: Build 
  jobs:
  - job: QaDeployJob
    steps:
    - bash: echo Job QaDeploy

- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QaDeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Job ProdDeploy


