FROM httpd:2.4
RUN apt-get -y update
RUN apt-get -y install php vim
#COPY ./index.html /usr/local/apache2/htdocs/
COPY ./index.sh /usr/local/apache2/cgi-bin/
RUN /bin/bash -c 'chmod 755 /usr/local/apache2/cgi-bin/index.sh' 
